// scalar/utils.rs — Utility functions for use in einsum-generated code.
//
// These are thin wrappers over [`Scalar`] trait methods and are kept `pub`
// so that code generated by the `einsum!` macro can call them without
// importing the trait itself.

use super::Scalar;

/// Additive identity for `T`.
#[must_use]
#[inline]
pub fn zero<T: Scalar>() -> T {
    T::zero()
}

/// Element-wise addition.
#[inline]
pub fn add<T: Scalar>(a: &T, b: &T) -> T {
    *a + *b
}

/// Element-wise multiplication.
#[inline]
pub fn mul<T: Scalar>(a: &T, b: &T) -> T {
    *a * *b
}

/// Complex conjugate (no-op for real types).
#[inline]
pub fn conj<T: Scalar>(a: &T) -> T {
    a.conj()
}

/// Absolute value (magnitude for complex types), returning the real component type.
#[inline]
pub fn abs<T: Scalar>(a: &T) -> T::Real {
    a.abs_val()
}

/// Convert an `f64` literal into any Scalar type.
#[must_use]
#[inline]
pub fn from_f64<T: Scalar>(v: f64) -> T {
    T::from_f64(v)
}
